# Aula 02 - Python 

## Dados numéricos 


In [6]:
# Variável inteira 
a = 1
print("Valor de a = "+ str(a))
type(a)

Valor de a = 1


int

In [7]:
# Variável dupla precisão
b = 1.0
print(b)
type(b)

1.0


float

In [8]:
# Converter float para int
c = int(b)
print(c)
type(c)

1


int

In [9]:
# Declarando NaN
import numpy as np
d = np.nan
print(d)
type(d)

nan


float

In [13]:
# Operação com NaN
e = d*1
print(e)
e = d+1
print(e)
e = np.nansum([d,1])
print(e)

nan
nan
1.0


## Dados de texto

In [17]:
# Declaração de variável de texto
f = 'Fabio'
g = "Gabriel"
print(f)
print(g)
print(f+g)
print(f+' '+g)

Fabio
Gabriel
FabioGabriel
Fabio Gabriel


## Dados tipo bool - lógica

In [18]:
a == 1

True

In [19]:
h = (a==1)
print(h)
type(h)

True


bool

In [20]:
h = (a==2)
print(h)
type(h)

False


bool

In [23]:
i = True
type(i)

bool

In [24]:
ii = "true"
type(ii)

str

In [30]:
# Operação ==
a==b

True

In [27]:
# Operação !=
a!=b

False

In [28]:
# Operação <>
a>b

False

In [29]:
# Operação <= ou >=
a<=b

True

# Operações matemáticas

In [32]:
# Soma
a+b

2.0

In [33]:
ab = a+b
print(ab)

2.0


In [36]:
# Multiplicação
l = a*b # Não usar l como variável (confunde com 1)
print("Não usar l como variável (confunde com 1)")
j = a*b
print(j)

Não usar l como variável (confunde com 1)
1.0


In [37]:
# Divisão
a/b

1.0

In [39]:
# Potência
5**a

5

In [41]:
# Operações matemáticas com a biblioteca math
import math

math.exp(10)

22026.465794806718

In [42]:
math.exp(a)

2.718281828459045

In [43]:
math.exp(0)

1.0

In [44]:
math.exp(-a)

0.36787944117144233

In [45]:
import math as mt
mt.exp(c)

2.718281828459045

In [46]:
mt.log(c)

0.0

In [47]:
mt.log10(100)

2.0

In [ ]:
# Listas

In [57]:
myFirstList = [1,2,3]
print(myFirstList)

[1, 2, 3]


In [52]:
# Acessando valores pelo index
print(myFirstList[0])
print(myFirstList[2])

1
3


In [53]:
myFirstList ==a

False

In [55]:
myFirstList[0]==a

True

In [59]:
mySecList = [1,a,"c"]
print(mySecList)

[1, 1, 'c']


In [60]:
type(mySecList)

list

In [61]:
type(mySecList[0])

int

In [62]:
type(mySecList[1])

int

In [63]:
type(mySecList[2])

str

## Caminhos - path

In [66]:
# Colocar r no começo do endereço para mudar as barras ao contrário
path = r"C:\Users\Windows 10\Documents\Python\ENS410064-1"
print(path)

C:\Users\Windows 10\Documents\Python\ENS410064-1


In [67]:
path = "C:/Users/Windows 10/Documents/Python/ENS410064-1"
print(path)

C:/Users/Windows 10/Documents/Python/ENS410064-1


In [68]:
import os
os.listdir(path)

['.git',
 '.gitignore',
 'Aula_01.ipynb',
 'dados',
 'pyenv',
 'README.md',
 'scripts']

In [69]:
os.listdir(path)[0]

'.git'

In [70]:
path+"/"+os.listdir(path)[0]

'C:/Users/Windows 10/Documents/Python/ENS410064-1/.git'

In [71]:
os.listdir(path+"/"+os.listdir(path)[0])

['COMMIT_EDITMSG',
 'config',
 'description',
 'FETCH_HEAD',
 'HEAD',
 'hooks',
 'index',
 'info',
 'logs',
 'objects',
 'packed-refs',
 'refs']

In [74]:
os.getcwd()

'C:\\Users\\Windows 10\\Documents\\Python\\ENS410064-1\\pyenv\\Scripts'

In [75]:
os.chdir('C:\\Users\\Windows 10\\Documents\\Python\\ENS410064-1\\')

In [76]:
os.getcwd()

'C:\\Users\\Windows 10\\Documents\\Python\\ENS410064-1'

In [96]:
new_path = os.mkdir(os.getcwd()+"/test2")

# Numpy arrays e Pandas DataFrames

In [98]:
import numpy as np
#Criando uma variável numpy
n = np.array(0)
type(n)

numpy.ndarray

In [99]:
#Criando numpy a partir de uma lista
myTList=[1,2,3,10,20,55]
n = np.array(myTList)
print(n)

[ 1  2  3 10 20 55]


In [103]:
# Criando uma matrix de 10x10 de números aleatórios entre 0 e 1
n = np.random.rand(10,10)
print(n)
# Dimensões da matriz
print(n.shape)

[[0.62137495 0.70272196 0.76867123 0.25288362 0.56901069 0.61690585
  0.21700757 0.57988303 0.61030666 0.5712625 ]
 [0.8668994  0.18881402 0.6597864  0.00858279 0.12805896 0.63065213
  0.22146384 0.54300827 0.95270479 0.26265618]
 [0.49898961 0.16950324 0.21533072 0.95596801 0.47040742 0.69632507
  0.459437   0.12959882 0.21099468 0.26215585]
 [0.08503985 0.62087394 0.35050406 0.06501695 0.86189742 0.52730941
  0.40903656 0.02524781 0.79680729 0.89311406]
 [0.76920111 0.62654455 0.6656911  0.17302501 0.74825168 0.47710097
  0.090085   0.00918012 0.67520018 0.69408093]
 [0.98089763 0.71661262 0.92410315 0.65537368 0.84902227 0.04056415
  0.54774559 0.18244347 0.13236373 0.35043987]
 [0.4403856  0.67488721 0.48966412 0.31962493 0.63839675 0.47724072
  0.22852576 0.27850669 0.2181804  0.92998527]
 [0.52735171 0.82305739 0.21881523 0.37787544 0.06120845 0.99869486
  0.09197219 0.34665655 0.14935013 0.86758825]
 [0.45718914 0.34217891 0.56306966 0.10173557 0.04870361 0.57125114
  0.32528082

In [105]:
# Acessando valores da matriz
n[0]

array([0.62137495, 0.70272196, 0.76867123, 0.25288362, 0.56901069,
       0.61690585, 0.21700757, 0.57988303, 0.61030666, 0.5712625 ])

In [106]:
n[1,4]

0.1280589649270064

In [107]:
n[:,0]

array([0.62137495, 0.8668994 , 0.49898961, 0.08503985, 0.76920111,
       0.98089763, 0.4403856 , 0.52735171, 0.45718914, 0.13531169])

In [108]:
n[0,:]

array([0.62137495, 0.70272196, 0.76867123, 0.25288362, 0.56901069,
       0.61690585, 0.21700757, 0.57988303, 0.61030666, 0.5712625 ])

In [110]:
n[:,1:5]

array([[0.70272196, 0.76867123, 0.25288362, 0.56901069],
       [0.18881402, 0.6597864 , 0.00858279, 0.12805896],
       [0.16950324, 0.21533072, 0.95596801, 0.47040742],
       [0.62087394, 0.35050406, 0.06501695, 0.86189742],
       [0.62654455, 0.6656911 , 0.17302501, 0.74825168],
       [0.71661262, 0.92410315, 0.65537368, 0.84902227],
       [0.67488721, 0.48966412, 0.31962493, 0.63839675],
       [0.82305739, 0.21881523, 0.37787544, 0.06120845],
       [0.34217891, 0.56306966, 0.10173557, 0.04870361],
       [0.24866836, 0.57995679, 0.04836186, 0.26978827]])

In [111]:
n[1,1:5]

array([0.18881402, 0.6597864 , 0.00858279, 0.12805896])

In [112]:
# Ultimo valor = -1
n[0,-1]

0.5712625013968178

In [113]:
# Vai da 4 ATÉ a última
n[0,4:-1]

array([0.56901069, 0.61690585, 0.21700757, 0.57988303, 0.61030666])

In [114]:
# Vai da 4 a última
n[0,4:]

array([0.56901069, 0.61690585, 0.21700757, 0.57988303, 0.61030666,
       0.5712625 ])

In [115]:
an = np.log(n)
print(an)

[[-4.75820593e-01 -3.52793967e-01 -2.63091929e-01 -1.37482588e+00
  -5.63856056e-01 -4.83038859e-01 -1.52782304e+00 -5.44928877e-01
  -4.93793732e-01 -5.59906453e-01]
 [-1.42832344e-01 -1.66699279e+00 -4.15839134e-01 -4.75799661e+00
  -2.05526446e+00 -4.61000872e-01 -1.50749597e+00 -6.10630728e-01
  -4.84501960e-02 -1.33690941e+00]
 [-6.95170011e-01 -1.77488325e+00 -1.53558021e+00 -4.50308321e-02
  -7.54156102e-01 -3.61938672e-01 -7.77753461e-01 -2.04331162e+00
  -1.55592237e+00 -1.33881610e+00]
 [-2.46463532e+00 -4.76627210e-01 -1.04838298e+00 -2.73310725e+00
  -1.48619016e-01 -6.39967782e-01 -8.93950732e-01 -3.67901591e+00
  -2.27142419e-01 -1.13040981e-01]
 [-2.62402827e-01 -4.67535404e-01 -4.06929531e-01 -1.75431911e+00
  -2.90015891e-01 -7.40027140e-01 -2.40700164e+00 -4.69071489e+00
  -3.92746076e-01 -3.65166705e-01]
 [-1.92871776e-02 -3.33219869e-01 -7.89315746e-02 -4.22549697e-01
  -1.63669865e-01 -3.20487065e+00 -6.01944345e-01 -1.70131491e+00
  -2.02220159e+00 -1.04856615e+00